language: java
before_script:
  - gradle wrapper
  - chmod +x gradlew
  - curl 'http://download.macromedia.com/pub/flashplayer/updaters/10/flashplayer_10_sa_debug.app.zip' >> flashplayer.zip
  - unzip flashplayer.zip
script:
  - ./gradlew build --stacktrace