before_script:
  - "wget http://repo.gradle.org/gradle/distributions/gradle-1.0-milestone-7-bin.zip"
  - "unzip gradle-1.0* > /dev/null"
  - curl 'http://download.macromedia.com/pub/flashplayer/updaters/10/flashplayer_10_sa_debug.app.zip' >> flashplayer.zip
  - unzip flashplayer.zip
script:
  - "gradle-1.0*/bin/gradle -q test"